'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class contact
    Public Property id As Decimal
    Public Property country As String
    Public Property prefix As String
    Public Property firstName As String
    Public Property lastName As String
    Public Property position As String
    Public Property institution As String
    Public Property department As String
    Public Property address As String
    Public Property email As String
    Public Property phone As String
    Public Property fax As String
    Public Property primary As Byte
    Public Property updated As Nullable(Of Date)

    Public Overridable Property treaties As ICollection(Of contacts_treaties) = New HashSet(Of contacts_treaties)

End Class
