'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class country_reports
    Public Property id As Decimal
    Public Property treaty As String
    Public Property country As String
    Public Property submission As Nullable(Of Date)
    Public Property url As String
    Public Property updated As Nullable(Of Date)

    Public Overridable Property title As ICollection(Of country_reports_title) = New HashSet(Of country_reports_title)

End Class
