'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class meeting
    Public Property id As Decimal
    Public Property treaty As String
    Public Property url As String
    Public Property start As Date
    Public Property [end] As Nullable(Of Date)
    Public Property repetition As String
    Public Property kind As String
    Public Property type As String
    Public Property access As String
    Public Property status As String
    Public Property imageUrl As String
    Public Property imageCopyright As String
    Public Property location As String
    Public Property city As String
    Public Property country As String
    Public Property latitude As Nullable(Of Double)
    Public Property longitude As Nullable(Of Double)
    Public Property updated As Nullable(Of Date)

    Public Overridable Property title As ICollection(Of meetings_title) = New HashSet(Of meetings_title)
    Public Overridable Property description As ICollection(Of meetings_description) = New HashSet(Of meetings_description)

End Class
