'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class site
    Public Property id As Decimal
    Public Property type As String
    Public Property country As String
    Public Property treaty As String
    Public Property name As String
    Public Property url As String
    Public Property latitude As Nullable(Of Double)
    Public Property longitude As Nullable(Of Double)
    Public Property updated As Nullable(Of Date)

    Public Overridable Property site_name As ICollection(Of sites_name) = New HashSet(Of sites_name)

End Class
